### ISSUE TITLE
Implement Ownership Claim on imported assets 

### ISSUE THREAD

**Issue by puria** [interfacerproject/interfacer-gui#103]
As per design: https://www.figma.com/file/VPQ54ZcJc8T0fveV7Q5uSs/Interfacer---FCOS-UI?node-id=735%3A27376
create or move the assets by assigning 0 Fab tokens.
On what kind of mutation and entity creation/manipulation we should ask better @sbocconi

**Comment by sbocconi** [comment]
Is my help still required here?
