### ISSUE TITLE
Sign-in and login are both used in a messy way 

### ISSUE THREAD

**Issue by andrea-dintino** [interfacerproject/interfacer-gui#172]
The sign in page takes you [here](https://gyazo.com/592e8104740b85e1386b5bbb711cb06f) offer you to "login". 
We need to be consisted with wording, it should be "sign-in" everywhere

**Comment by puria** [comment]
I do suggest considering `Login` and `Sign up`.
`Sign in` and `Sign up` are usually misleading to people that do not read everything carefully

**Comment by puria** [comment]
Actually did some small research in ux world and this what I more suggest:


!(long)[https://uxmovement.com/wp-content/uploads/2011/04/signup-vs-signin.png]

**Comment by puria** [comment]
We are talking about a margina 7% error anyway... but since we have to change things, why not stick to good habits ;p
