### ISSUE TITLE
Fix z-index on form selects

### ISSUE THREAD

**Issue by puria** [interfacerproject/interfacer-gui#281]

**Comment by puria** [comment]
![Screenshot 2022-12-15 232732](https://user-images.githubusercontent.com/10379/207981003-7ca160fd-437c-4407-9ea5-cd406cea4f20.png)

**Comment by bbtgnn** [comment]
closed by [3e96659](https://github.com/interfacerproject/interfacer-gui/commit/3e9665970e00930b713d1bcab376e2c1fdb8bd3a)
