### ISSUE TITLE
Starred UX feedback

### ISSUE THREAD

**Issue by jaromil** [interfacerproject/interfacer-gui#460]
When giving a project the star it turns into a message that looks almost like an error:
![image](https://user-images.githubusercontent.com/148059/220125151-9c8f5c24-e0a4-43a2-98c2-aacff402009f.png)

It is best to write "Starred!" - maybe even some sort of animation or a filled star

**Comment by micolsalomone** [comment]
as shown in the components: 
https://www.figma.com/file/VPQ54ZcJc8T0fveV7Q5uSs/Interfacer---FCOS-UI?node-id=879%3A35334&t=1kfuF9Mv26lbw8HL-1

<img width="895" alt="Schermata 2023-02-24 alle 15 01 06" src="https://user-images.githubusercontent.com/26438256/221197311-c733b45f-bde0-4e3d-9cd1-69f34f47d937.png">

**Comment by micolsalomone** [comment]
also the location of the star button is wrong, this is from the design: 
<img width="948" alt="Schermata 2023-02-24 alle 15 02 10" src="https://user-images.githubusercontent.com/26438256/221197717-418c94e2-95ca-479d-bd8c-29e087874b2e.png">

link: https://www.figma.com/file/VPQ54ZcJc8T0fveV7Q5uSs/Interfacer---FCOS-UI?node-id=1939%3A52626&t=1kfuF9Mv26lbw8HL-1

**Comment by phoebus-84** [comment]
Now the label it's Starred
