### ISSUE TITLE
Add visual diversity to new notifications

### ISSUE THREAD

**Issue by puria** [interfacerproject/interfacer-gui#493]
Distinct in a visual way, new notification in inbox, from the read or archived ones

**Comment by micolsalomone** [comment]
All users:
- contribution request (incoming)
- contribution answer (my contribution on another project)
- added as contributor
- mentions/relations

For "watch" followers [add "watched projects" category]:
- new contribution
- accepted / rejected 
- important edits (location, license, contributors, relations)
- contributors

**Comment by micolsalomone** [comment]
Updated notification component with "read" and "unread" status
https://www.figma.com/file/VPQ54ZcJc8T0fveV7Q5uSs/Interfacer---FCOS-UI?node-id=2128%3A57649&t=dTC6iIg8kxAPn9mq-1
