### ISSUE TITLE
Add OpenKnowHow on Project Page

### ISSUE THREAD

**Issue by micolsalomone** [interfacerproject/interfacer-gui#495]
Add OKH button to run the checker 
Allow the user to show the checker results, or not

related issues: #340 #321

**Comment by micolsalomone** [comment]
https://standards.internetofproduction.org/pub/okh#template

**Comment by micolsalomone** [comment]
As shown on the design: https://www.figma.com/file/VPQ54ZcJc8T0fveV7Q5uSs/Interfacer---FCOS-UI?node-id=879%3A36041&t=V6tq3xpEMfU58fNH-1 

In the components there are two variants:
- Project owner (logged in): can run the checker, show and hide some specifications
- Public users (not owners): see the checker results (if visible)
NOTE: If the owner sat all the specifications as hidden, the component is then not shown (or shown as empty? @puria )

<img width="1028" alt="Schermata 2023-02-27 alle 16 21 53" src="https://user-images.githubusercontent.com/26438256/221604499-0c7e474b-a68f-417f-a610-20019afc3de1.png">

**Comment by micolsalomone** [comment]
Remember to add version: 0.3.1-15-gbc9808f

**Comment by srfsh** [comment]
> @srfsh what is the new okh tool version number?

zenflows-osh includes the version 0.4.4: https://github.com/interfacerproject/zenflows-osh/blob/master/Dockerfile#L22
