### ISSUE TITLE
Edit images in project and profile

### ISSUE THREAD

**Issue by jaromil** [interfacerproject/interfacer-gui#545]
Upload new images to overwrite the ones used in project and profile pages.

**Comment by phoebus-84** [comment]
we need to change how we upload the images on zenflows to do that @srfsh

**Comment by jaromil** [comment]
the images are saved as `blob` in PSQL

⚠️ the implementation does not follow the file-upload scheme in zenflows-crypto

files are indexed by hash

**Comment by bbtgnn** [comment]
Profile images edit has been solved by #630 
Project images edit is tracked by #540
