### ISSUE TITLE
Generation of QR code as DPP data carrier

### ISSUE THREAD

**Issue by adam-burns** [interfacerproject/interfacer-gui#559]
A data carrier such as a QR code is a Digital Product Passport component that provides a machine readable format.

A Data Carrier, machine readable & contains:
- Product Identifier Code
- Location Reference to (URI) Linked Data
- Verifiable cryptographic authenticity & integrity data

Linked Data, including Identifier codes for:
- source components & materials
- manufacturers & manufacturing facilities
- (dis)assembly instructions

**Comment by jaromil** [comment]
A DPP should contain a minimal amount of signed information that can be verified non-interactively.

The signature should be from the zenflows node, and made with a BLS key following the REFLOW multi-signature using object's UID.

It will contain the following contents:
- zenflows node ID or URL
- object ID
- (multi) signature

The zenflows node should have an REST API endpoint accepting the object ID and replying with a DPP visualization graph.

The multi signature will contain more than one signature by more than one node in a federated environment.

**Comment by jaromil** [comment]
A non-verified way to show the DPP would be simply to export the https URL of the node with object id in the path or GET.

The endpoint will show the DPP visualizioation and a notice about non-verified content.
