### ISSUE TITLE
OKH checker goes in loop for 0638GM2RCFSQJJW51X1K9PZA4G ID

### ISSUE THREAD

**Issue by tm-miha** [interfacerproject/interfacer-gui#633]
OKH checker goes in loop for: https://beta.interfacer.dyne.org/project/0638GM2RCFSQJJW51X1K9PZA4G

**Comment by tm-miha** [comment]
Actually goes in error: 'Something went wrong be sure to have a valid repository url'

**Comment by puria** [comment]
To reproduce create a design by import https://github.com/CollectiveOpenSourceHardware/LibreSolarBox

and the run the OKH checker, it will hang

**Comment by puria** [comment]
This should be fixed by the upgrade of the osh-tool in the gateway... I'll close it
