### ISSUE TITLE
Contribution proposal page: change title composition and read pic from project

### ISSUE THREAD

**Issue by andrea-dintino** [interfacerproject/interfacer-gui#690]
(ref: #688 )

Contribution proposal page: 
- Use the title written before (ref: #688 ) as the name of the contribution, instead of "{original title} forked by {user}"
- the icon is broken, it should use the image of the projec being contributed. It's also broken when there is an image in the md file https://gyazo.com/b78b8d354dc051f578965b43d427ad37

**Comment by phoebus-84** [comment]
closed in #706 , now we force user to use an existing project, with its own image and its own title
