### ISSUE TITLE
Can't Signup

### ISSUE THREAD

**Issue by francoisAuclair126** [interfacerproject/interfacer-gui#772]
Hello, 

The signup process seems broken, once we answer the security question the next step button does not link anywhere. The issue seem not to be browser based.

Thanks

**Comment by tm-miha** [comment]
Hi, can I ask you what url u r using?
We had to do some infra cleaning and the most stable deployment is on https://interfacer.dyne.org/

**Comment by puria** [comment]
Is still an issue? I'll close this as no further info was provided!
In case is still an issue you are welcome to re-open it!
