### ISSUE TITLE
Import from LOSH created 2 times

### ISSUE THREAD

**Issue by tm-miha** [interfacerproject/interfacer-gui#775]
This 2 projects are identical and were created at the same time when importing form Losh 
https://interfacer.dyne.org/project/06595JASADX5Q6AMGAA0X8MS3R
https://interfacer.dyne.org/project/06595JB3FGEXGVG0M5D2M6J0B8

![image](https://github.com/interfacerproject/interfacer-gui/assets/67272885/122415d1-2744-4b6b-86bd-856c219d76db)

Same here:
![image](https://github.com/interfacerproject/interfacer-gui/assets/67272885/74b95057-b4f6-497b-896c-30e34357b018)

https://interfacer.dyne.org/project/064YA8XV20PEEKDEY7SRCKRCC0
https://interfacer.dyne.org/project/064YA8YA05BJT5AM5DYKG8J58R

**Comment by puria** [comment]
@tm-miha Didn't understand the actions you made... can you describe better? You claimed a losh project, and then two different DESIGN and PROJECT were created?

**Comment by tm-miha** [comment]
yes

**Comment by puria** [comment]
No prob. Will close this, as soon as new info is provided to replicate it we can reopen.
